#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Deploy collectd and rrdcached configurations on fresh install.
        echo "Deploy collectd and rrdcached configurations ..."
        omv-salt deploy run --no-color --quiet rrdcached collectd || :

        # generate graphs
        echo "Generating graphs ..."
        omv-mkrrdgraph || :

        # Activate package triggers.
        dpkg-trigger update-workbench
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
