#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    dpkg-trigger update-workbench
}

case "$1" in
    purge)
        remove_action
        # Remove generated configuration and scripts.
        rm -f /etc/openmediavault/cputemp.conf
        rm -f /usr/sbin/cpu-temp \
              /usr/sbin/cpu-temp2 \
              /usr/sbin/cpu-temp3 \
              /usr/sbin/cpu-temp4
        if omv_config_exists "/config/services/cputemp"; then
            omv_config_delete "/config/services/cputemp"
        fi
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
