#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Deploy collectd configuration on fresh install.
        if [ -z "$2" ]; then
            omv-salt deploy run --no-color --quiet rrdcached collectd || :
        fi
        # Activate package triggers.
        dpkg-trigger update-workbench
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
