#!/bin/sh
#
# Copyright (C) 2022-2026 openmediavault plugin developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Collectd exec plugin script for CPU temperature monitoring.
# Reads up to 4 CPU temperatures and outputs data in collectd PUTVAL format.

HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"
INTERVAL="${COLLECTD_INTERVAL:-60}"

# Source generated configuration (written by salt).
if [ -r /etc/openmediavault/cputemp.conf ]; then
    . /etc/openmediavault/cputemp.conf
fi

SCRIPT1="${SCRIPT1:-/usr/sbin/cpu-temp}"
DIVISOR1="${DIVISOR1:-1000}"
SCRIPT2="${SCRIPT2:-/usr/sbin/cpu-temp2}"
DIVISOR2="${DIVISOR2:-1000}"
SCRIPT3="${SCRIPT3:-/usr/sbin/cpu-temp3}"
DIVISOR3="${DIVISOR3:-1000}"
SCRIPT4="${SCRIPT4:-/usr/sbin/cpu-temp4}"
DIVISOR4="${DIVISOR4:-1000}"

emit_temp() {
    LABEL="$1"
    SCRIPT="$2"
    DIV="$3"

    [ -x "$SCRIPT" ] || return
    [ "$DIV" = "0" ] && DIV=1

    TEMP_RAW=$("$SCRIPT" 2>/dev/null | head -1 | tr -d '[:space:]')
    if [ -n "$TEMP_RAW" ]; then
        VALUE=$(awk "BEGIN {printf \"%.3f\", $TEMP_RAW / $DIV}" 2>/dev/null)
        if [ -n "$VALUE" ]; then
            echo "PUTVAL \"$HOSTNAME/exec-cputemp${LABEL}/temperature-value\" interval=$INTERVAL N:$VALUE"
        fi
    fi
}

while true; do
    emit_temp ""  "$SCRIPT1" "$DIVISOR1"
    emit_temp "2" "$SCRIPT2" "$DIVISOR2"
    emit_temp "3" "$SCRIPT3" "$DIVISOR3"
    emit_temp "4" "$SCRIPT4" "$DIVISOR4"
    sleep "$INTERVAL"
done
